version       = "0.0.5"
author        = "guzba"
description   = "An in-progress GLTF viewer."
license       = "MIT"
srcDir        = "src"

requires "nim >= 1.0.0"
requires "opengl >= 1.2.3"
requires "staticglfw >= 4.1.2"
requires "pixie >= 1.1.2"
requires "flatty >= 0.2.1"
